#!/bin/sh

echo $(pwd -P)

# https://github.com/travis-ci/docs-travis-ci-com/issues/949
# https://github.com/travis-ci/travis-rubies/blob/9f7962a881c55d32da7c76baefc58b89e3941d91/build.sh#L38-L44
fold_start() {
  echo -e "travis_fold:start:$1\033[33;1m$2\033[0m"
}

fold_end() {
  echo -e "\ntravis_fold:end:$1\r"
}

# Create a build folder.
[ -d ./Build ] && rm -r ./Build
mkdir ./Build

fold_start "xcode.debug.test"
xcodebuild -workspace cocoadialog.xcworkspace -scheme Debug test | tee ./Build/xcodebuild-debug-test.log | xcpretty -f `xcpretty-travis-formatter`
fold_end "xcode.end"

fold_start "xcode.release.build"
xcodebuild -workspace cocoadialog.xcworkspace -scheme Release build | tee ./Build/xcodebuild-release-build.log | xcpretty -f `xcpretty-travis-formatter`
fold_end "xcode.release"
