#!/bin/sh

echo $(pwd -P)

# Create a build folder.
[ -d ./Build ] && rm -r ./Build
mkdir ./Build

xcodebuild -workspace cocoadialog.xcworkspace -scheme Debug test | tee ./Build/xcodebuild-debug-test.log | xcpretty -f `xcpretty-travis-formatter`

xcodebuild -workspace cocoadialog.xcworkspace -scheme Release build | tee ./Build/xcodebuild-release-build.log | xcpretty -f `xcpretty-travis-formatter`
